//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploadAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductImage
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ImagePath { get; set; }
        public string FileName { get; set; }
        public string MimeType { get; set; }
        public Nullable<long> FileSize { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
